### PR TITLE
Google maps (Bootcamp)

### PR DESCRIPTION
**Pull request by Pyr0ss**

### CODE REVIEW

**Review by MichaelFrmn — COMMENTED** [review]
Overall, the code looks functional and well-written. One improvement that I can think of is that you could add a null safety check since the findFragmentById method can return a null object if the fragment is not found.

**Review by DavidTheCourtyard — COMMENTED** [review]
It's sad that I can not test it manually because we don't have a shared API key unrelated to any payment account but I don't think it is worth to make one now since we won't use google map for the project. There is not a lot of tests but I guess it is because google map classes are final and it is hard to test them. Did you try to play with Polylines et polygones? We could use these classes for the drawing in our project. Good code otherwise and thank you for your pull request

**Comment by Pyr0ss** [comment]
> Overall, the code looks functional and well-written. One improvement that I can think of is that you could add a null safety check since the findFragmentById method can return a null object if the fragment is not found.

Thanks for your feedback, I'll try to think about these checks in the future !

**Comment by Pyr0ss** [comment]
> Did you try to play with Polylines et polygones? We could use these classes for the drawing in our project. 

I don't think this is the optimal way to go for the drawing part of our project, but I'll keep this option in mind if I ever need it. Thanks for the review!

**Pull request closed without merging**
