### PR TITLE
untested fireApp use set and get and 2 textfields to reach realtime database

### PR DESCRIPTION
**Pull request by DavidTheCourtyard**
Hey here is my first pull request feel free to roast my code!

It is a an untested App that use set and get and 2 textfields to reach a realtime database.

### CODE REVIEW

**Review by GitC0der — COMMENTED** [review]
Just a few comments or remarks: I think it’s good that your setAndGet test goes through a series of steps to verify the fire app’s functionality. Regarding the names of the defined functions, such as get, set, updateEmailAndPhone, setDB, etc. they seem to be straightforward and easy to understand.
Of course, the Android tests would need to succeed before this can be accepted, but otherwise I have nothing to report.

**Review by MichaelFrmn — COMMENTED** [review]
Overall, the code seems to be well-structured and easy to read. However I noticed there were a few unused variable which could be removed. Also, adding some comments would increase readability in my opinion.

**Comment by DavidTheCourtyard** [comment]
I wrote the tests:
package bootcamp.fireapp
import androidx.test.espresso.Espresso.onView
import androidx.test.espresso.action.ViewActions.*
import androidx.test.espresso.assertion.ViewAssertions.matches
import androidx.test.espresso.matcher.ViewMatchers.withId
import androidx.test.espresso.matcher.ViewMatchers.withText
import androidx.test.ext.junit.rules.ActivityScenarioRule
import androidx.test.ext.junit.runners.AndroidJUnit4
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
@RunWith(AndroidJUnit4::class)
class FireAppTest {
    private val ENTER_KEY: Int = 66
    @get:Rule
    var testRule = ActivityScenarioRule(
        MainActivity::class.java
    )

    @Test
    fun setAndGet() {
        onView(withId(R.id.phone)).perform(clearText())
        onView(withId(R.id.phone)).perform(typeText("FireAppTestSetAndGetKey"))
        onView(withId(R.id.phone)).perform(pressKey(ENTER_KEY))
        onView(withId(R.id.email)).perform(clearText())
        onView(withId(R.id.email)).perform(typeText("FireAppTestSetAndGetValue"))
        onView(withId(R.id.email)).perform(pressKey(ENTER_KEY))
        onView(withId(R.id.set)).perform(click())
        onView(withId(R.id.email)).perform(clearText())
        onView(withId(R.id.get)).perform(click())
        onView(withId(R.id.email)).check(matches(withText("FireAppTestSetAndGetValue")))
    }
}

**Comment by DavidTheCourtyard** [comment]
Should I redo a branch that would be merge into the main for the demo?

**Comment by MichaelFrmn** [comment]
Firebase is now set up via another pull request. Are you all ok to close this pull request ?

**Comment by GitC0der** [comment]
Yes, I would agree. Let's close it.

**Pull request closed without merging**
