### PR TITLE
Connect Timer with database

### PR DESCRIPTION
**Pull request by ctaverni**
This branch was originally for creating an activity for joigning or creating a game, but Michael already did it. 
So I just add some design in this activity, and I used this branch for another issue : connecting the timer with the database. 

The "current" data of the game now contains a "current_timer" parameter, which can be "unused", "inprogress" or "over". The DrawingActivity send "inprogress" to the database when lauched, and "over" when the timer is over. 
And the GuessingActivity listens to it, and remove the possible to make guesses and instead a popup window with "the timer is over!".  At the same time, the artist can't draw anymore, and the same pop-up appears.

### CODE REVIEW

**Comment by DavidTheCourtyard** [comment]
hey, in case you didn't notice I thin the android tests doesn't pass on the CI.

**Review by MichaelFrmn — CHANGES_REQUESTED** [review]
The code is well documented and understandable. However, the feature seems to be working at first, but whenever I try to create a game and launch it, the guesser's screen crashes and restarts before going to the GuessingActivity. The following error occurs :

image

**Comment by ctaverni** [comment]
@DavidTheCourtyard I don't know why it happend. It showed me they passed first. So I just re-ran the tests and it works. Let me know if they finally don't passed. 

@MichaelFrmn Thank you for pointing out that problem ! I first chose first to make the current_timer a boolean after changing it to a String, and I forgot to make a necessary change. It is normally fixed.

**Review by MichaelFrmn — APPROVED** [review]
Your modifications fixed the bug. Everything works as expected now. Good job !

**Pull request merged**
